### ISSUE TITLE
Clash with MidiQOL with game canvas disabled

### ISSUE THREAD

**Issue by amcvfx** [theripper93/Levels#86] opened 2022-04-10 15:56 UTC
Hi,
I have found an edge case issue when running MiqiQOL and Levels, when the Game Canvas is disabled (for players using laptops for only character sheets at an in person game).
They are unable to use items in their characters sheets as it throws this error when they are clicked. Not sure if this is a Levels issue or MidiQOL but the error only occurs when both modules are active. I'm also going to post the issue to MidiQOL.

![levelsMidiQOL error](https://user-images.githubusercontent.com/35099081/162628080-764c8127-3396-4b2c-bbd0-92ea6dd5548b.JPG)

Foundry VTT 9,255
Levels 2.7.2
MidiQOL 0.9.44

Other modules active:
Better Roofs
Find the Culprit
Wall Height
lipwrapper
socketlib

**Comment by theripper93** [comment] 2022-04-10 16:26
Levels will fail to initialize with canvas disabled but that specific error is caused by midiqol I’ll close the issue here

**Closed by theripper93** 2022-04-10 16:26 UTC
