### ISSUE TITLE
[BUG] When logged as Trusted Player / Player, deleting a token from levels scene causes a crash.

### ISSUE THREAD

**Issue by Zimnior12** [theripper93/Levels#160] opened 2024-10-15 22:23 UTC
**I have disabled all other modules:** True
**Module(s)**
levels 5.3.10
**Conflicting Module(s)**
**Foundry and System version**
Foundry v12 331 D&D 3.3.1
**OS, Hosting, Browser (if applicable)**
Win 11, Linux, Tested on Chrome and VTTDesktop Client (by TheRipper93)
**Short description of bug**
When logged as Trusted Player / Player, deleting a token from levels scene causes a crash. The same issue is not happening while logged as Gamemaster. Tested on a few maps and it seems to be always related to levels. My players reported that they crash whenever they want to delete their token and that's how I have discovered this issue. As a GM I have never encountered this issue. This issue was happening on earlier version of the module  (5.3.8)
**Simple steps to reproduce the bug**

1. Login to Foundry as Player/Trusted Player.
2. Place token on a map with levels enabled.
3. Delete your token.

**Screenshots and/or Console Errors**

https://github.com/user-attachments/assets/f331f17e-5d3d-4414-971c-e75cbaf18baf

[foundry.zimnyte.com-1729030654597.log](https://github.com/user-attachments/files/17386432/foundry.zimnyte.com-1729030654597.log)

**Comment by theripper93** [comment] 2024-10-15 22:32
From the error i see, the issue you are describing looks like a bug with foundry core, i don't see any mention of levels in that error. If i'm mistaken and it's indeed levels feel free to reopen the issue but it looks a lot like a core bug to me. Test with 0 modules

**Comment by Zimnior12** [comment] 2024-10-15 22:43
When I disabled all modules the issue is gone. Then restarted foundry with just levels, LibWrapper and wall height and the crash came back.

Tried new world and the issue doesn't seem to really be there... I don't really know how to trigger this on new world but I will try to reproduce maps I create and see if there are any issues.

**Comment by Zimnior12** [comment] 2024-10-15 22:49
Ok. I think I got what's the issue? I made a brand new world, added background image, added levels, uploaded the top floor of the map. Everything was fine and not crashing.

After I added walls to my scene it started crashing again. All tested on brand new world.

https://github.com/user-attachments/assets/0769604a-7c95-4312-b40e-ce01eeee38e0

**Comment by Zimnior12** [comment] 2024-10-15 22:50
Adding logs from the new world just in case.

[foundry.zimnyte.com-1729030424123.log](https://github.com/user-attachments/files/17386562/foundry.zimnyte.com-1729030424123.log)

**Comment by theripper93** [comment] 2024-10-15 22:54
> Ok. I think I got what's the issue? I made a brand new world, added background image, added levels, uploaded the top floor of the map. Everything was fine and not crashing.
> 
> After I added walls to my scene it started crashing again. All tested on brand new world.
> 
>  thorium_Dn79wUXims.mp4

are you able to repeat this procedure an trigger the issue again?

**Comment by theripper93** [comment] 2024-10-15 23:03
did you test with just wall height?

**Comment by Zimnior12** [comment] 2024-10-15 23:05
Reproduced the entire thing from nothing and recorded the process. It's more than 10MB so I uploaded to streamable.

https://streamable.com/h63lxp

Also will test wall height just in a moment.

**Comment by Zimnior12** [comment] 2024-10-15 23:07
With Wall Height just enabled the issue is not present. Seems like it's related to levels.

**Comment by theripper93** [comment] 2024-10-15 23:10
Can you also verify if the same problem occurs if you use the included farm map instead of importing and making your own?

**Comment by theripper93** [comment] 2024-10-15 23:17
Ok, i managed to reproduce, i'll take it over from here- thanks for the info

**Comment by Zimnior12** [comment] 2024-10-15 23:20
Tested with assets just included with 5e module. Same issue.

https://github.com/user-attachments/assets/a08bbaf0-bd21-4593-a94e-11ff3bd91ab9



> Ok, i managed to reproduce, i'll take it over from here- thanks for the info

Sure thing, Thanks for bearing with me on this. Really enjoying your module so I would love to see stuff fixed 👍

**Comment by theripper93** [comment] 2024-10-15 23:49
fixed in https://github.com/theripper93/Levels/releases/tag/5.3.11

**Closed by theripper93** 2024-10-15 23:49 UTC
