### ISSUE TITLE
Tokenscale not working for Holes

### ISSUE THREAD

**Issue by Koalahund** [theripper93/Levels#13] opened 2021-06-14 05:13 UTC
Foundry 0.8.6
PF1 0.78.9
Levels 0.5.9

Tokenscale doesn't work with holes as player, looks fine as gm.
Using Width and Height works fine.

Scale outside of hole:
![188c3c233c32ea7ff17688a5089eb184](https://user-images.githubusercontent.com/85458282/121841725-3726e000-ccdf-11eb-8158-28b207161a22.png)

Scale inside hole:
![1497ed5a13b9f3a7154fa1470e35c62e](https://user-images.githubusercontent.com/85458282/121841758-486fec80-ccdf-11eb-80b6-8c1cb8e62ea0.png)

**Comment by theripper93** [comment] 2021-06-14 10:59
i don't seem to have this issue

![image](https://user-images.githubusercontent.com/1346839/121882037-4eca8c80-cd10-11eb-8c94-80acbb1c54a8.png)

**Comment by theripper93** [comment] 2021-06-14 11:01
never mind, the issue is there, fixed in next release!

**Closed by theripper93** 2021-06-14 11:01 UTC
