### ISSUE TITLE
Bug in 1.9.9.6: modifying a tile causes player to temporarily ignore light sources of tokens

### ISSUE THREAD

**Issue by Merudo** [theripper93/Levels#68] opened 2021-11-29 10:23 UTC
When the GM modifies a tile (e.g. adding a tile, hiding/showing the tile, or moving it around), players temporarily ignore the light source of tokens, resulting in fog instead of light.

If there are no other light sources, this can cause players to lose all visions.

The light sources become active again for a player if they reselect their own token.

To reproduce:

1. Enable only the Levels module and its dependencies
2. Put a player token on a map without any light, and give that token a light source but no dark vision.
3. As a player, connect to the game and take control of the player token.
4. As a GM, interact with a tile.
5. As a player, tokens will have apparently lost their light sources.
6. Reselect the token as a player to use the light sources again.

**Comment by Merudo** [comment] 2021-11-29 10:28
Example: normal vision for player. The token is carrying a light source illuminating the dungeon.

![image](https://user-images.githubusercontent.com/7371085/143851418-d80e4384-472f-469c-a236-b69f34028d55.png)

After changing from hidden to visible:

![image](https://user-images.githubusercontent.com/7371085/143851556-6e786cd3-033a-48ee-acd3-f12192382e4f.png)

**Comment by theripper93** [comment] 2021-11-29 12:04
The issue is already fixed in the v9 version of levels, it will not be fixed for foundry 0.8.x I’m afraid

**Closed by theripper93** 2021-11-29 12:04 UTC
